### ISSUE TITLE
Cannot read property 'PureComponent' of undefined

### ISSUE THREAD

**Issue by arnelap** [felixboet/netlify-cms-widget-colorpicker#2]
Hi,

I'm trying to use the widget with 

<script src="https://unpkg.com/netlify-cms-widget-color@^0.1.0"></script>
<script>CMS.registerWidget("color", ColorControl);</script>

but I am getting the following errors on the browser console: 

netlify-cms-widget-color@^0.1.0:1 Uncaught TypeError: Cannot read property 'PureComponent' of undefined
    at netlify-cms-widget-color@^0.1.0:1
    at Object.NetlifyCMSColorWidget (netlify-cms-widget-color@^0.1.0:1)
    at r (netlify-cms-widget-color@^0.1.0:1)
    at Object.NetlifyCMSColorWidget (netlify-cms-widget-color@^0.1.0:1)
    at r (netlify-cms-widget-color@^0.1.0:1)
    at Object.<anonymous> (netlify-cms-widget-color@^0.1.0:1)
    at r (netlify-cms-widget-color@^0.1.0:1)
    at Object.NetlifyCMSColorWidget (netlify-cms-widget-color@^0.1.0:1)
    at r (netlify-cms-widget-color@^0.1.0:1)
    at Object.NetlifyCMSColorWidget (netlify-cms-widget-color@^0.1.0:1)
(anonymous) @ netlify-cms-widget-color@^0.1.0:1
NetlifyCMSColorWidget @ netlify-cms-widget-color@^0.1.0:1
r @ netlify-cms-widget-color@^0.1.0:1
NetlifyCMSColorWidget @ netlify-cms-widget-color@^0.1.0:1
r @ netlify-cms-widget-color@^0.1.0:1
(anonymous) @ netlify-cms-widget-color@^0.1.0:1
r @ netlify-cms-widget-color@^0.1.0:1
NetlifyCMSColorWidget @ netlify-cms-widget-color@^0.1.0:1
r @ netlify-cms-widget-color@^0.1.0:1
NetlifyCMSColorWidget @ netlify-cms-widget-color@^0.1.0:1
r @ netlify-cms-widget-color@^0.1.0:1
NetlifyCMSColorWidget @ netlify-cms-widget-color@^0.1.0:1
(anonymous) @ netlify-cms-widget-color@^0.1.0:1
(index):16 Uncaught ReferenceError: ColorControl is not defined
    at (index):16

I noticed the closed issue and it had a link to code I should include, but that link goes to a 404. 

Thanks for your help!

**Comment by felixboet** [comment]
Hi Arne, sorry, still struggling to get the NPM module running. The code I mentioned moved to [here](https://github.com/felixboet/netlify-cms-widget-colorpicker/blob/master/src/ColorControl.js)

**Comment by felixboet** [comment]
... I just updated to version 0.1.1 ... should be working now

**Comment by arnelap** [comment]
Thanks for the update!

Should I now work with the script tag? or still need to do the manual import as mentioned in the other issue?
With the script tag I now get 

netlify-cms-widget-colorpicker@^0.1.1:3 Uncaught ReferenceError: exports is not defined
    at netlify-cms-widget-colorpicker@^0.1.1:3
(anonymous) @ netlify-cms-widget-colorpicker@^0.1.1:3
(index):19 Uncaught ReferenceError: ColorControl is not defined
    at (index):19

It has to go through babel first?

**Comment by felixboet** [comment]
Yep, seems like the script tag isn't working, i did't try that. Took it out of the docs for now. You need to install the npm module.

**Comment by felixboet** [comment]
Close for now, i'll create a UMD version as soon as I have time
