### ISSUE TITLE
z-index of color picker is too low

### ISSUE THREAD

**Issue by kierenfunk** [felixboet/netlify-cms-widget-colorpicker#5]
![Screenshot_2020-10-14 Screenshot](https://user-images.githubusercontent.com/22581965/95949340-ff0e8b00-0e39-11eb-923f-8cbeaed3fbef.png)

Color picker is hidden by other widgets with a higher z-index.
Suggestion is to increase the z-index to some value greater than 200, which is the z-index of the markdown widget block.

**Comment by felixboet** [comment]
Thanks Kieren, I will fix that. In your screenshot I also realized, that the questionmark doesn't look as it should. On which system are you? I just tried on Mac. Or maybe better change it to an SVG￼.

**Comment by felixboet** [comment]
fixed with version 1.0.3 ... closing for now, please reopen if there is still any issue.
